README.md

PR 一个readme

---

packages/valaxy-theme-yun/components/YunConfig.vue
packages/valaxy-theme-yun/components/YunToggleLocale.vue
packages/valaxy/client/locales/en.yml
packages/valaxy/client/locales/zh-CN.yml

* Fix typo in English.
* Fix misspelled entries.
* For `toggle_dark` it just does not seem right, since the context here is clearly switching theme between `light` and `theme` so using **toggle** here made sense, but `dark` should really be `theme` here which matches the context.
* `toggle_langs` here is quite wrong, since `toggle` something is either **on** or **off**, languages are not booleans, which is enumerable so we should use **change** or **switch**.
* The rest updates are just some minor updates.

chore(locale): adjustments for the locale

---

packages/valaxy/node/cli.ts
packages/valaxy/node/cli/new.ts

- Add new command for generate new posts via cli.
- Add new folder cli for cli commands.

feat(cli): introduce `new` command for generating post

---

packages/valaxy/node/cli/new.ts
packages/valaxy/node/cli/utils/fs.ts
packages/valaxy/node/cli/utils/post.ts

* Setup skeleton of CLI tool for generating new post.

feat(cli): new post utility

---

packages/valaxy/node/cli/utils/post.ts
packages/valaxy/package.json
pnpm-lock.yaml

* Add `ejs` for replacing template posts.
* Refine creating template post method with `ejs`.

feat(cli): introducing ejs for templating

---

packages/valaxy/client/config.ts
packages/valaxy/types/config.ts

- wrong type of useConfig #28 
- theme config type read abnormal #34 
Question about type-fest: 
https://github.com/YunYouJun/valaxy/issues/34#issuecomment-1179577037

fix: type display exception under typescript

---

packages/valaxy/README.md
packages/valaxy/client/scaffolds/post.md
packages/valaxy/docs/en/creating-templates.md
packages/valaxy/node/cli/utils/constants.ts
packages/valaxy/node/cli/utils/post.ts
packages/valaxy/node/cli/utils/scaffold.ts

* Introduced scaffolding mechanism for generating new post.
* Add docs on how to create new template.
* Refine post file for adapting new mechanism.

feat(cli): add scaffolding for generating new post

---

packages/valaxy/node/cli/utils/post.ts
packages/valaxy/node/cli/utils/scaffold.ts

* Allow reading scaffold from userRoot and themeRoot.

feat(cli): [new-post] adding support for userRoot and themeRoot

---

packages/valaxy-theme-press/components/PressAside.vue
packages/valaxy-theme-press/components/PressToc.vue
packages/valaxy-theme-press/components/ValaxyMain.vue
packages/valaxy-theme-press/layouts/layout.vue
packages/valaxy-theme-press/styles/css-vars.scss

Hey, this is for the aside of the valaxy-theme-press, good night ^^

feat: add aside to valaxy-theme-press

---

packages/valaxy/node/plugins/preset.ts
packages/valaxy/node/types.ts

feat: extends md add content

---

README.md
README.zh-CN.md

1. Create and translate into Simplified Chinese README from English README ( #118 )
2. Correct the first feature to Vite 3

Update Simplified Chinese README & change to Vite 3

---

demo/yun/valaxy.config.ts
packages/create-valaxy/template/valaxy.config.ts

https://github.com/travellings-link/travellings/issues/1347

chore: update travellings link

---

packages/valaxy-theme-yun/components/YunFooter.vue
packages/valaxy-theme-yun/node/config.ts
packages/valaxy-theme-yun/types/index.d.ts

fix: footer icon & footer layout

---

docs/pages/guide/config.md

我认为这是每个使用博客主题的人都想去修改的东西，它应该出现在配置示例里。

docs(config.md): set site icon and subtitle

---

docs/pages/guide/deploy.md

添加 Vercel / Cloudflare Pages 部署教程以及其翻译

docs: add deploy guide

---

packages/valaxy/node/markdown/plugins/markdown-it/preWrapper.ts

https://github.com/YunYouJun/valaxy/issues/291

fix: code copy

---

packages/valaxy-addon-meting/node/index.ts

fix: meting options fix type and field invalid

---

docs/pages/guide/markdown.md

docs: Chineseized markdown.md

---

docs/pages/guide/markdown.md

docs: Update markdown.md

---

README.md
README.zh-CN.md

Update README.md & README.zh-CN.md

docs: fix broken link in README

---

docs/pages/guide/third-party/comment-system.md

The structure of document: `comment-system.md` is wrong, `Utterances` title should be second level

docs: wrong document structure in comment-system.md

---

docs/pages/guide/built-ins/index.md

Complete the English translation  of the Components chapter.

docs: complete the English translation  of the Components chapter

---

packages/valaxy-addon-bangumi/components/ValaxyBangumi.vue
packages/valaxy-addon-bangumi/index.d.ts
packages/valaxy-addon-bangumi/package.json

feat: adapt themes to bangumi component

---

packages/valaxy-addon-bangumi/package.json
pnpm-lock.yaml

chore: update bilibili-bangumi-component dependencies

---

packages/valaxy-addon-bangumi/components/ValaxyBangumi.vue
packages/valaxy-addon-bangumi/types/index.ts

https://github.com/yixiaojiu/bilibili-bangumi-component/issues/5

feat: customCSS for addon-bangumi

---

demo/yun/valaxy.config.ts
packages/valaxy-addon-bangumi/README.md
packages/valaxy-addon-bangumi/package.json
packages/valaxy-theme-yun/components/YunComment.vue
packages/valaxy-theme-yun/components/YunSelect.vue
packages/valaxy-theme-yun/components/third/YunTwikoo.vue
pnpm-lock.yaml

https://github.com/YunYouJun/valaxy/issues/310

feat: double comment and bangumi addon docs

---

packages/valaxy-addon-meting/README.md
packages/valaxy-addon-meting/client/hook.ts
packages/valaxy-addon-meting/client/index.ts
packages/valaxy-addon-meting/client/observer.ts
packages/valaxy-addon-meting/client/options.ts
packages/valaxy-addon-meting/client/utils.ts
packages/valaxy-addon-meting/index.d.ts
packages/valaxy-addon-meting/node/index.ts
packages/valaxy-addon-meting/style/animation-in.scss

- feat: Add configuration to hide lyrics on startup
- feat: Add auto-hide configuration for APlayer
- feat: Add configuration to show APlayer after loading is complete

feat: add custom enhancements

---

docs/components/AddonGallery.vue
docs/components/AddonGalleryCard.vue
docs/pages/addons/gallery.md

Add more Valaxy Addons and include descriptions in Chinese

feat: add more valaxy addons with chinese descriptions

---

packages/valaxy-addon-components/README.md
packages/valaxy-addon-components/README.zh-CN.md
packages/valaxy-addon-components/core/resolvers.ts
packages/valaxy-addon-components/index.ts
packages/valaxy-addon-components/package.json

This PR introduces a new `ValaxyThemesResolver`, enabling seamless integration of third-party theme components. And updated the `valaxy-addon-components` documentation

feat(addon-components): add ValaxyThemesResolver

---

packages/valaxy/node/cli/clean.ts
packages/valaxy/node/cli/index.ts

命令行中添加clean命令，用于清除dist文件夹与缓存
win11系统中自测截图

feat: add clean command

---

docs/package.json
docs/public/git-log.json
docs/valaxy.config.ts
pnpm-lock.yaml

link https://github.com/valaxyjs/valaxy-addon-git-log/issues/5

docs: support pre-generated git-log in builds

---

README.md
README.zh-CN.md

[English Template / 英文模板](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1)
新版展示图表展示如下：

docs: update a new contributions charts

---

packages/valaxy/node/modules/rss/utils.ts
packages/valaxy/package.json
pnpm-lock.yaml

This is a lightweight, zero-dependency feed library I built. It's a rewrite of `feed`, with further optimizations to the implementation based on the specification.

refactor(valaxy): migrate to `zfeed`

---

packages/valaxy-theme-yun/tsconfig.json

- resolve valaxy/client type resolution
---

fix: change moduleResolution from node to bundler
