demo/yun/pages/posts/design.md
demo/yun/pages/posts/dev.md
demo/yun/pages/posts/draft.md
demo/yun/pages/posts/hello-valaxy.md
demo/yun/pages/posts/index.md
demo/yun/pages/posts/toc.md
packages/valaxy/src/client/locales/zh-CN.yml

1. Delete redundant complex number content in Chinese
2. Translate the articles in `demo/yun/pages/posts/` into English
And here is a question.
How can I make titles of articles internationalized?

No complex number in Chinese & Example articles in English

---

packages/valaxy-theme-press/components/nav/PressNavBar.vue
packages/valaxy-theme-press/components/nav/PressSwitchAppearance.vue
packages/valaxy-theme-press/styles/css-vars.scss

Modify the style of the dark mode switch, from single button to sliding switch.

feat(theme-press): beautify the sun-moon switch btn

---

test/addon.test.ts
test/config.test.ts
test/md.test.ts
test/utils.test.ts
tsconfig.json
vitest.config.ts

Signed-off-by: Sepush <sepush@outlook.com>
set `globals: true ` like jest so that we don't need to import in every test files

chore: set vitest globals to true

---

packages/valaxy-theme-press/styles/css-vars.scss
packages/valaxy-theme-yun/layouts/tags.vue

1. Do not wrap when overflowing ( theme yun )
Before:
After adding .break-words (overflow-wrap: break-word;):
2. nav was covered with local-nav ( #114 ) ( theme press )
3. ~~Incorrect style of `PressAside.vue` ( #84 ) ( theme press )~~

fix: auto wrap for tags page, close #114

---

packages/valaxy-theme-press/styles/markdown.scss

Code tags have back quotes

---

docs/pages/guide/deploy.md

使用 Github Action 自动部署工作流，不设置 docs 中描述的配置，可能会出现如下错误。
> 我不确定现在的仓库是否会自动设置权限
配置仓库权限后，部署成功，如下图。

docs(deploy.md): requested URL returned error: 403

---

docs/pages/guide/deploy.md

1. 采用 github actions 部署时， 应该先让 github actions 能正常生成 gh-pages 分支后，才可以设置 `page`  为 `gh-pages`
2. `注意修改` 那部分内容，没有被 ::: zh-CN 包裹。

chore: fix deploy about github page

---

docs/components/ThemeGallery.vue
docs/locales/en.yml
docs/locales/zh-CN.yml
docs/pages/guide/deploy.md
docs/pages/themes/gallery.md

完成 文档的 gallery 页面展示
ps：为什么 我在本地仓库同步上游分支并且merge后， 就多了两个 commit
Merge remote-tracking branch 'upstream/main'
chore: fix deploy about github page (#221)
实际只有最新的 commit，改变了 4 个文件。

docs: improve the gallery page

---

packages/valaxy-addon-meting/App.vue
packages/valaxy-addon-meting/README.md
packages/valaxy-addon-meting/package.json

Global meting music player
```ts
import { defineConfig } from 'valaxy'
export default defineConfig({
addons: [
['valaxy-addon-meting', {
props: {
/** @see https://github.com/metowolf/MetingJS */
}
}]
]
})
```
you can [meting#options](https://github.com/metowolf/MetingJS#option)

feat: add valaxy-addon-meting package

---

docs/pages/guide/deploy.md

部署到cf pages部分的步骤似乎缺少了设置构建命令步骤，可能导致部署时无法构建

docs: update guide deploy

---

packages/valaxy-addon-meting/client/observer.ts
packages/valaxy-addon-meting/client/utils.ts
packages/valaxy-addon-meting/package.json

onMounted should only be used within the setup function, otherwise it may lead to abnormal component behavior. The useEventListener function already handles component unmounting logic by default

fix(valaxy-addon-meting): abnormal configuration of music player

---

packages/valaxy-addon-meting/client/hook.ts
packages/valaxy-addon-meting/client/styles/animation-in.scss
packages/valaxy-addon-meting/package.json
packages/valaxy-addon-meting/style/animation-in.scss

I apologize for the error. The module was tested within the theme project instead of a single blog test, which led to the mistake. Specifically, enabling the `animationIn` option resulted in the error `Cannot find module xxx`. To ensure proper module import, I added `onMounted`. Additionally, I took the opportunity to update the formatting standards in the `animation-in.scss` file.

fix: dynamic scss import functionality

---

packages/valaxy-addon-bangumi/components/ValaxyBangumi.vue
packages/valaxy-addon-bangumi/package.json

Restored `valaxy-addon-bangumi` to a basic working state.
At this line, the following error occurs:
https://github.com/YunYouJun/valaxy/blob/a58ca38fa765f99c4740890d92099e779cecc4a3/packages/valaxy-addon-bangumi/components/ValaxyBangumi.vue#L10
```
Uncaught (in promise) SyntaxError: The requested module '/@fs/home/wrxinyue/Documents/my_project/valaxy-theme-sakura/node_modules/.pnpm/bilibili-bangumi-component@0.3.0/node_modules/bilibili-bangumi-component/dist/cjs/loader.cjs.js?v=29b10672' does not provide an export named 'defineCustomElements' (at ValaxyBangumi.vue:2:10)
```
In this case, a wildcard import should be used:
```js
import * as bilibiliBangumi from 'bilibili-bangumi-component/dist/cjs/loader.cjs';
bilibiliBangumi.defineCustomElements();
```
However, this change causes a …

fix(addon-bangumi): runtime error in browser

---

packages/valaxy-theme-yun/layouts/post.vue

修复当全局开启 copyright 显示时，在单篇文章中禁用无效的问题

fix: copyright frontmatter doesn't work

---

packages/valaxy-theme-yun/components/YunFuseSearch.vue
packages/valaxy-theme-yun/components/YunSearchBtn.vue
packages/valaxy-theme-yun/components/YunSearchTrigger.vue
packages/valaxy-theme-yun/composables/helper.ts
packages/valaxy/client/composables/index.ts
packages/valaxy/client/composables/search/fuse.ts
packages/valaxy/client/composables/search/index.ts
packages/valaxy/node/config/site.ts
packages/valaxy/node/modules/fuse.ts
packages/valaxy/node/types.ts
packages/valaxy/types/config.ts
packages/valaxy/types/node.ts

- Added: New `useFuseSearch` composables to facilitate developer calls
- Added: Added `extendKeys` configuration item to extend the fields obtained by search
- Fixed: [yun] Fixed the issue where `isLocked` was ineffective in the yun theme
- Changed: `keys` no longer extends the field 'content', but uses `extendKeys` for field extension
- Changed: [yun] Updated the search code for the yun theme and encapsulated the hotkey tool
```vue
<script lang="ts" setup>
import { onMounted, ref } from 'vue'
import { useFuseSearch } from 'valaxy'
const input = ref()
const { results } = useFuseSearch(input)
</script>
<template>
<input v-model="input">
</template>
````
```ts
import { defineSiteConfig } from 'valaxy'
export default defineSiteConfig({
fuse: {
extendKeys: ['cover'],
},
})
```

feat: add search components & enhancements

---

packages/valaxy-theme-press/components/PressMenuLink.vue
packages/valaxy-theme-press/components/PressNavItemGroup.vue
packages/valaxy-theme-press/components/PressNavItemGroupChild.vue
packages/valaxy-theme-press/types/index.d.ts

https://github.com/YunYouJun/valaxy/issues/477

feat:Add support for group in the nav configuration of the press theme

---

packages/valaxy-theme-yun/components/YunFooter.vue
packages/valaxy-theme-yun/node/config.ts
packages/valaxy-theme-yun/types/index.d.ts

Currently, the `banner.cloud.enable` configuration option appears to have no effect.
After comparing `valaxy-theme-yun` with [hexo-theme-yun](https://github.com/YunYouJun/hexo-theme-yun) , I noticed that the dynamic cloud feature has been moved from the bottom of the homepage to the top of the footer on all pages. To address this, I’ve introduced a new configuration option, `footer.cloud.enable`, which allows users to toggle this feature on or off.
To avoid any potential breaking changes, I have not modified the original `banner.cloud.enable` configuration option.

feat(valaxy-theme-yun): make footer dynamic cloud configurable

---

packages/valaxy-addon-waline/components/WalineClient.vue
packages/valaxy-addon-waline/types/index.ts
packages/valaxy-addon-waline/utils/index.ts

#520 解决emoji表情选项卡问题
增加 `types`，`emoji` 参数

fix(addon-waline): 插件无法显示 emoji 表情选项卡的问题

---

packages/valaxy/node/plugins/markdown/plugins/markdown-it/katex.ts
packages/valaxy/node/plugins/markdown/plugins/markdown-it/snippet.ts
packages/valaxy/node/plugins/markdown/transform/hexo.ts

This PR addresses three critical bugs in markdown processing plugins, ensuring proper handling of Hexo tags, KaTeX rendering, and code snippet token types.
Hexo bug: String immutability issue where replacements weren't being applied
KaTeX bug: Incorrect conditional logic in error handling that caused warnings to always display
Snippet bug: Type safety violations that were being suppressed rather than properly handled
1. **Hexo bug**:
- Fixed by assigning the result of `replaceAll` calls to ensure replacements are applied
- Used `replaceAll` instead of `replace` to handle all occurrences
2. **KaTeX bug**:
- Corrected the error handling logic to conditionally throw errors based on `throwOnError` option
- Removed the empty statement after `if` condition
3. **Snippet bug**:
- Added type …

Fix: Markdown Plugin Bugs - Hexo Tag Escaping, KaTeX Error Handling, and Snippet Type Safety Issues

---

README.md
docs/pages/addons/write.md
docs/pages/dev/docs.md
docs/pages/guide/deploy.md
docs/pages/guide/third-party/index.md
docs/pages/guide/why.md

1. Fixed 4 instances of incorrect article usage ("a" → "an" before vowel sounds)  
- README.md: "For a example" → "For an example"  
- addons/write.md: "Write a Addon" → "Write an Addon"  
- guide/third-party/index.md: "in a article" → "in an article"  
- dev/docs.md: "This is a example" → "This is an example"  
2. "read and write permissions。" to  "read and write permissions."
3. Fixed "archieved" → "archived" in docs/pages/guide/why.md

docs: fix grammatical errors and spelling issues in documentation  

---

playwright.config.ts

- Update playwright.config.ts baseURL from https://localhost:4859 to http://localhost:4859,resolve SSL certificate warnings
- Aligns with actual dev server configuration which runs on HTTP：`playwright.config.ts:87`
In `dev.ts:57`, the server is configured with `host: remote ? '0.0.0.0' : 'localhost'` and there is no HTTPS configuration.
Although the documentation mentions that page encryption requires HTTPS (docs/pages/guide/page.md), this is a requirement for production environments, not test environments.

test(e2e): change baseURL from HTTPS to HTTP for localhost testing

---

demo/custom/valaxy-theme-custom/components/StarterArticle.vue
packages/valaxy-theme-yun/components/YunSearchTrigger.vue
packages/valaxy-theme-yun/components/menu/YunNavMenuTitle.vue
packages/valaxy-theme-yun/components/third/YunAlgoliaSearch.vue
packages/valaxy/node/plugins/preset.ts

1. Fixed i18n display error on nav's menutitle (fyi I have attached the image to reveal the problem):
2. In addition, the algolia hot key is not enabled when first mounted in `theme-yun`
3. The group icons are not working appropriatly for code blocks in `theme-yun`
1. N/A, refer to https://github.com/YunYouJun/valaxy/commit/051e7fcf5064a0f5e9b416302d0ffc71ae72c96a
2. See #567 and https://github.com/WRXinYue/valaxy/commit/4a416642d0fffc1836b5a067137df8b425b83de6
3. See #557 and https://github.com/YunYouJun/valaxy/commit/f8f0e8df22b1b35699399d4d4330233d81cde12f

fix: i18n title for themes + algolia hot key for theme-yun

---

packages/valaxy-theme-yun/components/YunPostCard.vue

The post card was way too compact when it exhibits the html content of a post
After adding some paddings, it gets better
N/A

feat(theme-yun): add padding to post card to reduce compactness

---

packages/valaxy/node/plugins/markdown/plugins/markdown-it/titleCollector.ts
packages/valaxy/node/plugins/markdown/setup.ts
packages/valaxy/node/plugins/preset.ts

fix: inject default labels to support custom code block icons at correct timing, close #578
Cannot inject the correct default labels to the custom icon plugin, which leads to lost custom code block icons
#578 and #573

fix: inject default labels to support custom code block icons at correct timing

---

packages/valaxy/client/components/ValaxyDynamicComponent.vue

DynamicComponent that loads the excerpt_html on the home page view caches the rendered output based on the templateStr, so even if we change the templateStr later, the component won't render the new template.
#583

fix: excerpt_html dynamicComponent cache issue, close #583

---

packages/devtools/src/node/functions.ts

When using node:path, backslashes are used by default in Windows environments. However, according to [fast-glob#237](https://github.com/mrmlnc/fast-glob/issues/237), fast-glob doesn't support backslashs to match files. So I replace all backslashs with forward slashs to make fast-glob work normally.
I also find that backslashs are included in the route path, so I also replace all backslashs with forward slashs.

fix(devtools): backslash in windows not supported by fast-glob
